// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// crps_ensemble
NumericVector crps_ensemble(NumericMatrix ens, NumericVector obs);
RcppExport SEXP _ensGAN_crps_ensemble(SEXP ensSEXP, SEXP obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ens(ensSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type obs(obsSEXP);
    rcpp_result_gen = Rcpp::wrap(crps_ensemble(ens, obs));
    return rcpp_result_gen;
END_RCPP
}
// crps_ensemble_fast
NumericVector crps_ensemble_fast(NumericMatrix ens, NumericVector obs);
RcppExport SEXP _ensGAN_crps_ensemble_fast(SEXP ensSEXP, SEXP obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ens(ensSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type obs(obsSEXP);
    rcpp_result_gen = Rcpp::wrap(crps_ensemble_fast(ens, obs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ensGAN_crps_ensemble", (DL_FUNC) &_ensGAN_crps_ensemble, 2},
    {"_ensGAN_crps_ensemble_fast", (DL_FUNC) &_ensGAN_crps_ensemble_fast, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ensGAN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
