// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// crps_ensemble
NumericVector crps_ensemble(NumericMatrix ens, NumericVector obs);
RcppExport SEXP _ensGAN_crps_ensemble(SEXP ensSEXP, SEXP obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ens(ensSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type obs(obsSEXP);
    rcpp_result_gen = Rcpp::wrap(crps_ensemble(ens, obs));
    return rcpp_result_gen;
END_RCPP
}
// crps_ensemble_fast
NumericVector crps_ensemble_fast(NumericMatrix ens, NumericVector obs);
RcppExport SEXP _ensGAN_crps_ensemble_fast(SEXP ensSEXP, SEXP obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ens(ensSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type obs(obsSEXP);
    rcpp_result_gen = Rcpp::wrap(crps_ensemble_fast(ens, obs));
    return rcpp_result_gen;
END_RCPP
}
// compute_centred_coord_array
List compute_centred_coord_array(int M, int N);
RcppExport SEXP _ensGAN_compute_centred_coord_array(SEXP MSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_centred_coord_array(M, N));
    return rcpp_result_gen;
END_RCPP
}
// fft_swap_up_down
ComplexMatrix fft_swap_up_down(ComplexMatrix input_matrix);
RcppExport SEXP _ensGAN_fft_swap_up_down(SEXP input_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< ComplexMatrix >::type input_matrix(input_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(fft_swap_up_down(input_matrix));
    return rcpp_result_gen;
END_RCPP
}
// fft_swap_left_right
ComplexMatrix fft_swap_left_right(ComplexMatrix input_matrix);
RcppExport SEXP _ensGAN_fft_swap_left_right(SEXP input_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< ComplexMatrix >::type input_matrix(input_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(fft_swap_left_right(input_matrix));
    return rcpp_result_gen;
END_RCPP
}
// fftshift
ComplexMatrix fftshift(ComplexMatrix input_matrix, int dim);
RcppExport SEXP _ensGAN_fftshift(SEXP input_matrixSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< ComplexMatrix >::type input_matrix(input_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(fftshift(input_matrix, dim));
    return rcpp_result_gen;
END_RCPP
}
// ifft_swap_up_down
ComplexMatrix ifft_swap_up_down(ComplexMatrix input_matrix);
RcppExport SEXP _ensGAN_ifft_swap_up_down(SEXP input_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< ComplexMatrix >::type input_matrix(input_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(ifft_swap_up_down(input_matrix));
    return rcpp_result_gen;
END_RCPP
}
// ifft_swap_left_right
ComplexMatrix ifft_swap_left_right(ComplexMatrix input_matrix);
RcppExport SEXP _ensGAN_ifft_swap_left_right(SEXP input_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< ComplexMatrix >::type input_matrix(input_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(ifft_swap_left_right(input_matrix));
    return rcpp_result_gen;
END_RCPP
}
// ifftshift
ComplexMatrix ifftshift(ComplexMatrix input_matrix, int dim);
RcppExport SEXP _ensGAN_ifftshift(SEXP input_matrixSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< ComplexMatrix >::type input_matrix(input_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(ifftshift(input_matrix, dim));
    return rcpp_result_gen;
END_RCPP
}
// fftfreq
NumericVector fftfreq(int n, double d);
RcppExport SEXP _ensGAN_fftfreq(SEXP nSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(fftfreq(n, d));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ensGAN_crps_ensemble", (DL_FUNC) &_ensGAN_crps_ensemble, 2},
    {"_ensGAN_crps_ensemble_fast", (DL_FUNC) &_ensGAN_crps_ensemble_fast, 2},
    {"_ensGAN_compute_centred_coord_array", (DL_FUNC) &_ensGAN_compute_centred_coord_array, 2},
    {"_ensGAN_fft_swap_up_down", (DL_FUNC) &_ensGAN_fft_swap_up_down, 1},
    {"_ensGAN_fft_swap_left_right", (DL_FUNC) &_ensGAN_fft_swap_left_right, 1},
    {"_ensGAN_fftshift", (DL_FUNC) &_ensGAN_fftshift, 2},
    {"_ensGAN_ifft_swap_up_down", (DL_FUNC) &_ensGAN_ifft_swap_up_down, 1},
    {"_ensGAN_ifft_swap_left_right", (DL_FUNC) &_ensGAN_ifft_swap_left_right, 1},
    {"_ensGAN_ifftshift", (DL_FUNC) &_ensGAN_ifftshift, 2},
    {"_ensGAN_fftfreq", (DL_FUNC) &_ensGAN_fftfreq, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ensGAN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
