# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crps_ensemble <- function(ens, obs) {
    .Call(`_ensGAN_crps_ensemble`, ens, obs)
}

crps_ensemble_fast <- function(ens, obs) {
    .Call(`_ensGAN_crps_ensemble_fast`, ens, obs)
}

